name: frontend

on:
  push:
    branches:
      - main

jobs:
  myprojectDeploy:
    runs-on: ubuntu-latest

    # Dependencies install
    steps:
      - name: git library
        uses: actions/checkout@v4

      - name: ssh connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            cd /home/palak/seedlyfrntd 
            git pull origin main
            sudo npm i
            sudo npm run build
            pm2 delete "Seedly Frontend"
            pm2 start npm --name "Seedly Frontend" -- run dev || pm2 restart "Seedly Frontend"
